### PR TITLE
Disable content grid child switches when service switch is off

### LINKED ISSUE #1: Change all child switches to off while parent switch is off
In the Media sharing settings, it's not entirely clear that things are not being shared when the big switch is turned off. While the big switch at the top is off, we should also toggle the other switches to off.

Launchpad Details: [#LP1527835](https://bugs.launchpad.net/bugs/1527835) Daniel Fore - 2015-12-19 06:47:44 +0000

### PR DESCRIPTION
**Pull request by tjchester**
Resolves #1 - Change all child switches to off when parent switch is off

### CODE REVIEW

**Comment by ryonakano** [comment]
I think this is intentional. By not changing the state of child switches when the service switch turns off, users can restore their customized sharing setting just by turning on the service switch again.

**Comment by tjchester** [comment]
I updated the PR description to include the issue link. If as @ryonakano suggested that we wanted to preserve the user's sharing settings, as an alternative we could just hide the content-grid when the service is disabled.

**Comment by ryonakano** [comment]
@tjchester Thank you for quoting the issue link! We seem to need some discussion about the design.

**Comment by jeremypw** [comment]
@tjchester Closing as has unaddressed issues and no recent activity. Please feel free to reopen (as draft) if you wish to continue working on it.

**Pull request closed without merging**
